name: Zscanner IAC Scan
on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
env:
  AUTH_URL: "https://dev-auth.zscwp.io"
  API_URL: "https://main.dev.api.zscwp.io"
jobs:
  zscaler-iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name : Code Checkout
        uses: actions/checkout@v2
      - name : Zscaler IAC Scan
        uses : ZscalerCWP/Zscaler-IaC-Action@CWP-23516
        id : zscaler-iac-scan
        with:
          client_id : b7D6GHwSCqrPZ7XPyyprnoRgSpY6JsdL
          client_secret : sSaT8KQBjVOuw1zgQ9U_dn4EPk_hygeoYukuPAzKMZvf_LGHpbUtNICqTg5RgdQX
          region : 'CUSTOM'
          output_format : 'json'
          fail_build : 'false'
      - name: Upload SARIF file
        if: ${{ success() || failure() && (steps.zscaler-iac-scan.outputs.sarif_file_path != '') }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path }}
         
