name: Zscanner IAC Scan
on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
env:
  AUTH_URL: "https://dev-auth.zscwp.io"
  API_URL: "https://main.dev.api.zscwp.io"
jobs:
  zscaler-iac-scan:
    runs-on: ubuntu-latest
    outputs:
      var_Project: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path }}
    steps:
      - name : Code Checkout
        uses: actions/checkout@v2
      - name : Zscaler IAC Scan
        uses : ZscalerCWP/Zscaler-IaC-Action@tarun-test
        id : zscaler-iac-scan
        with:
          client_id : tu4BqKEGnGBUUbOrmF1uKHuzQGtQrqkx
          client_secret : BbNJdT_HQCVu0fVLqfQE8ek1NSCwO19SkNkJtw-2Dm732VtnZ_XY9UhQkZKgXepY
          region : 'CUSTOM'
          output_format : 'json+github-sarif'
          fail_build : 'true'
      - name: Upload SARIF file
        if: ${{ success() || failure() && steps.zscaler-iac-scan.outputs.sarif_file_path != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path }}

         
