name: Zscanner IAC Scan
on:
  push:
    branches: '*'
  pull_request:
env:
  AUTH_URL: "https://dev-auth.zscwp.io"
  API_URL: "https://main.dev.api.zscwp.io"
jobs:
  zscaler-iac-scan:
    runs-on: ubuntu-latest
    outputs:
      var_Project: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path }}
    steps:
      - name : Code Checkout
        uses: actions/checkout@v2
      - name : Zscaler IAC Scan
        uses : ZscalerCWP/Zscaler-IaC-Action@main
        id : zscaler-iac-scan
        with:
          client_id : gRLisrfR884v3WqQBQdm4m6jExs1Jqh4
          client_secret : VmgghrNGXdqR1Q3ItBfpnHtO_MBj0vUUHMqtFmMlBVxrvOnSs_Ug51SF1xWfNqCC
          region : 'CUSTOM'
          fail_build : 'true'
          output_format : 'json+github-sarif'
      - name: Upload SARIF file
        if: ${{ success() || failure() && steps.zscaler-iac-scan.outputs.sarif_file_path != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path }}
          


         
