name: Zscanner IAC Scan
on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
env:
  AUTH_URL: "https://dev-auth.zscwp.io"
  API_URL: "https://main.dev.api.zscwp.io"
jobs:
  zscaler-iac-scan:
    runs-on: ubuntu-latest
    outputs:
      var_Project: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path }}
    steps:
      - name : Code Checkout
        uses: actions/checkout@v2
      - name : Zscaler IAC Scan
        uses : ZscalerCWP/Zscaler-IaC-Action@tarun-test
        id : zscaler-iac-scan
        with:
          client_id : XUvcQOG02optJlWailotj5awVYB5RpS1
          client_secret : FLNCaBL6jKX8rUhi6ozU0hKtcpjay39KfvNojUfpU4KTTL5AHIWNJtMA6YNWeCWS
          region : 'CUSTOM'
          output_format : 'json+github-sarif'
          fail_build : 'true'
      - name: "Say Hello Mona it's Monday"
        run: echo "Greeting $env:GITHUB_OUTPUT"
      - name: Upload SARIF file
        if: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path }}
  job2:
    runs-on: ubuntu-latest
    needs: zscaler-iac-scan
    steps:
      - run: echo ${{needs.zscaler-iac-scan.outputs.var_Project}}
         
