name: Zscanner IAC Scan
on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
env:
  AUTH_URL: "https://int-auth.zscwp.io"
  API_URL: "https://int.api.zscwp.io"
jobs:
  zscaler-iac-scan:
    runs-on: ubuntu-latest
    outputs:
      var_Project: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path }}
    steps:
      - name : Code Checkout
        uses: actions/checkout@v2
      - name : Zscaler IAC Scan
        uses : ZscalerCWP/Zscaler-IaC-Action@CWP-59209
        id : zscaler-iac-scan
        with:
          client_id : UV7uwfg7a5Xx0O39HuKJTkQa7aJzuLkV
          client_secret : sgNoPD1SSmHTcE1iafby36pOjlH3hPPbJWRVWOJDgtjH7QIMEA0HfApWLpPngvWT
          region : 'CUSTOM'
          output_format : 'json+github-sarif+test'
          fail_build : 'true'
      - name: Upload SARIF file
        if: ${{ success() || failure() && steps.zscaler-iac-scan.outputs.sarif_file_path != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.zscaler-iac-scan.outputs.sarif_file_path }}

         
